encoding: bom|utf-8

title: Your awesome title
email: sammetok@yandex.ru
phones:
  - 8 (927) 011 06 27
  - 8 (927) 260 02 77
  - 8 (846) 990 02 77
address: "Самара, ул. Революционная, 101 А"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/metallvsamare"
# baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com


plugins:
  - jekyll-feed
  # - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-datapage-generator

exclude:
  - README.md
  - mix-manifest.json
  - package.json
  - src
  - webpack.mix.js
  - yarn.lock
  - docker-compose.yml
  - package-lock.json
  - tailwind.config.js

page_gen-dirs: true

page_gen:
  - data: 'works'
    template: 'single'
    name: 'uid'
    dir: 'works'
    # filter_condition: "record['categories'] == 'kovka'"

collections:
  work-categories:
    output: true
    permalink: /:path/

# defaults:
#   -
#     scope:
#       path: ""
#       type: "pages"
