version: "3"

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll_${APP_CONTAINER_NAME}
    command: jekyll serve --trace --watch --force_polling
    ports:
      - ${APP_CONTAINER_PORT}4:4000
    volumes:
      - .:/srv/jekyll